
import React, { createContext, useState, useContext, ReactNode } from 'react';
import type { Language } from '../types';

const translations = {
  cs: {
    app_title: "Fotograf AI",
    nav_studio: "Studio",
    nav_upload: "Nahrát fotky",
    nav_raw: "RAW Konvertor",
    nav_analysis: "AI Analýza",
    nav_manual: "Manuální úpravy",
    nav_batch: "Batch zpracování",
    nav_presets: "Uživatelské presety",
    nav_autopilot: "Autopilot AI",
    nav_remove_obj: "Odstranit objekt",
    nav_crop: "Automatické oříznutí",
    nav_style: "Přenos stylu",
    nav_bg: "Vyměnit pozadí",
    nav_gen: "Vytvořit obrázek",
    nav_export: "Export",
    nav_history: "Historie",
    nav_social: "Social Media Kit",
    nav_video: "Video (Veo)",
    nav_youtube: "YouTube Miniatury",
    
    turbo_culling: "Smart Culling",
    turbo_culling_desc: "AI analyzuje kvalitu a vybere nejlepší snímky.",
    turbo_run_culling: "Spustit technickou analýzu",
    turbo_best_pick: "AI Favorit",
    turbo_bad_quality: "Pozor: Snížená kvalita",
    turbo_express: "Turbo Workflow",
    turbo_express_desc: "Jedním klikem: Autopilot + Ořez + Popisky.",
    turbo_express_btn: "Spustit Turbo Workflow",
    
    home_title: "Fotograf AI",
    home_subtitle: "Profesionální workflow pro fotografy. Šetřete čas, tvořte umění a mějte hotovo v mžiku.",
    home_enter: "Vstoupit do studia",
    
    upload_title: "Nahrát fotky",
    upload_drag: "Přetáhněte fotografie sem",
    upload_support: "Podpora JPG, PNG, WEBP a",
    upload_raw: "RAW soubory budou automaticky vyvolány a převedeny.",
    upload_btn: "Vybrat soubory",
    upload_processing: "Zpracovávám soubory...",
    
    editor_no_image: "Žádný vybraný obrázek",
    editor_upload_hint: "Nahrajte nebo vyberte obrázek pro zahájení úprav.",
    editor_analyzing: "Analyzuji...",
    editor_desc: "Popis",
    editor_suggestions: "Návrhy na vylepšení",
    editor_proactive: "Proaktivní návrhy",
    editor_tech: "Technické informace",
    
    tool_autopilot_desc: "AI automaticky vylepší váš obrázek. Zachová strukturu a zaměří se na barvy a světlo.",
    tool_autopilot_btn: "Spustit Autopilot",
    tool_remove_desc: "Popište objekt, který chcete odstranit.",
    tool_remove_placeholder: "např. 'modré auto v pozadí'",
    tool_remove_btn: "Odstranit",
    tool_crop_title: "Chytrý Ořez",
    tool_crop_instr: "Instrukce pro AI (Volitelné)",
    tool_crop_placeholder: "např. 'Ořízni na detail obličeje'",
    tool_crop_format: "Cílový formát",
    tool_crop_btn_only: "Pouze Oříznout",
    tool_crop_btn_export: "Oříznout a exportovat",
    tool_bg_desc: "Popište nové pozadí.",
    tool_bg_placeholder: "např. 'rušná ulice v Tokiu'",
    tool_bg_btn: "Vyměnit pozadí",
    tool_style_desc: "Vyberte obrázek, jehož styl chcete aplikovat.",
    tool_style_select: "Vybrat obrázek stylu",
    tool_style_btn: "Aplikovat styl",

    tool_social_title: "Social Media Assistant",
    tool_social_desc: "AI vytvoří poutavé popisky a hashtagy pro váš Instagram.",
    tool_social_btn: "Generovat texty",
    
    tool_video_title: "Oživení fotky (Veo)",
    tool_video_desc: "Vytvořte z fotky video pomocí AI modelu Veo.",
    tool_video_prompt: "Popište pohyb (např. 'filmový zoom')",
    tool_video_btn: "Generovat Video",

    tool_youtube_title: "YouTube Thumbnail Creator",
    tool_youtube_desc: "Vytvořte virální náhledovku s vysokým kontrastem.",
    tool_youtube_topic: "Téma videa",
    tool_youtube_topic_ph: "např. Recenze iPhone 16",
    tool_youtube_text: "Text na miniatuře",
    tool_youtube_text_ph: "např. ŠOKUJÍCÍ PRAVDA",
    tool_youtube_face: "Použít aktuální fotku jako tvář",
    tool_youtube_btn: "Generovat Miniaturu",
    
    manual_title: "Manuální úpravy",
    manual_reset: "Resetovat",
    manual_crop_active: "Aktivovat manuální ořez",
    manual_brightness: "Jas",
    manual_contrast: "Kontrast",
    manual_saturation: "Sytost",
    manual_vibrance: "Živost",
    manual_shadows: "Stíny",
    manual_highlights: "Světlé tóny",
    manual_clarity: "Zřetelnost",
    manual_sharpness: "Ostrost",
    manual_noise: "Redukce šumu",
    manual_export_settings: "Nastavení Exportu",
    manual_finish: "Dokončit a Exportovat",

    export_title: "Exportovat obrázek",
    export_format: "Formát",
    export_quality: "Kvalita",
    export_size: "Velikost",
    export_original: "Původní",
    export_half: "Poloviční",
    export_download: "Stáhnout obrázek",

    batch_title: "Hromadné zpracování",
    batch_subtitle: "Aplikujte AI vylepšení na více obrázků najednou.",
    batch_select: "Vyberte obrázky",
    batch_selected: "vybráno",
    batch_select_all: "Označit vše",
    batch_deselect_all: "Odznačit vše",
    batch_run: "Spustit Autopilot na",
    batch_processing: "Zpracovávám...",
    batch_error: "Chyba při zpracování",
    batch_complete: "Zpracování dokončeno.",

    gen_title: "Vytvořte cokoliv s AI",
    gen_subtitle: "Popište obrázek a nechte AI tvořit.",
    gen_prompt: "Popis obrázku",
    gen_placeholder: "např. Astronaut na koni na Marsu",
    gen_btn: "Generovat obrázek",
    gen_generating: "Generuji...",
    gen_add: "Přidat do projektu",
    
    raw_title: "RAW Konvertor",
    raw_subtitle: "Hromadná konverze profesionálních RAW souborů.",
    raw_convert: "Konvertovat",
    raw_converting: "Analyzuji a převádím",
    raw_add: "Přidat do Studia",
    raw_convert_more: "Převést další",
    raw_done: "Konverze dokončena",
    raw_drag: "Přetáhněte RAW soubory sem",
    raw_or_click: "nebo klikněte pro výběr",
    raw_select_other: "Vybrat jiné",
    raw_no_files: "Nebyly vybrány žádné soubory.",
    
    modal_api_title: "Nastavení Google Gemini API",
    modal_api_desc: "Vložte vlastní API klíč pro komunikaci s AI.",
    modal_api_btn_auto: "Vybrat API klíč (Google AI Studio)",
    modal_api_manual_toggle: "Vložit klíč manuálně",
    modal_api_manual_label: "API klíč",
    modal_api_btn_save: "Uložit a Pokračovat",
    modal_api_footer: "Získat ho můžete zdarma v",

    msg_api_missing: "API klíč chybí.",
    msg_success: "Akce dokončena.",
    msg_error: "Došlo k chybě.",
    notify_upload_success: "souborů nahráno.",
    notify_gen_success: "Obrázek vygenerován.",
    notify_raw_success: "souborů připraveno.",

    compare_before: "Před",
    compare_after: "Po",
    compare_btn: "Porovnat"
  },
  en: {
    app_title: "Fotograf AI",
    nav_studio: "Studio",
    nav_upload: "Upload Photos",
    nav_raw: "RAW Converter",
    nav_analysis: "AI Analysis",
    nav_manual: "Manual Edits",
    nav_batch: "Batch Processing",
    nav_presets: "User Presets",
    nav_autopilot: "Autopilot AI",
    nav_remove_obj: "Remove Object",
    nav_crop: "Auto Crop",
    nav_style: "Style Transfer",
    nav_bg: "Replace Background",
    nav_gen: "Generate Image",
    nav_export: "Export",
    nav_history: "History",
    nav_social: "Social Media Kit",
    nav_video: "Video (Veo)",
    nav_youtube: "YouTube Thumbnails",

    turbo_culling: "Smart Culling",
    turbo_culling_desc: "AI analyzes quality and picks the best shots.",
    turbo_run_culling: "Run Quality Assessment",
    turbo_best_pick: "AI Favorite",
    turbo_bad_quality: "Warning: Poor Quality",
    turbo_express: "Turbo Workflow",
    turbo_express_desc: "One click: Autopilot + Crop + Social.",
    turbo_express_btn: "Run Turbo Workflow",
    
    home_title: "Fotograf AI",
    home_subtitle: "Professional workflow for photographers. Save time, create art, and get done in a flash.",
    home_enter: "Enter Studio",
    
    upload_title: "Upload Photos",
    upload_drag: "Drag & Drop photos here",
    upload_support: "Supports JPG, PNG, WEBP and",
    upload_raw: "RAW files will be automatically converted.",
    upload_btn: "Select Files",
    upload_processing: "Processing files...",
    
    editor_no_image: "No image selected",
    editor_upload_hint: "Upload an image to start editing.",
    editor_analyzing: "Analyzing...",
    editor_desc: "Description",
    editor_suggestions: "Suggestions",
    editor_proactive: "Proactive Suggestions",
    editor_tech: "Technical Info",
    
    tool_autopilot_desc: "Let AI automatically enhance your image.",
    tool_autopilot_btn: "Run Autopilot",
    tool_remove_desc: "Describe object to remove.",
    tool_remove_placeholder: "e.g. 'blue car'",
    tool_remove_btn: "Remove",
    tool_crop_title: "Smart Crop",
    tool_crop_instr: "AI Instructions",
    tool_crop_placeholder: "e.g. 'Crop to the face'",
    tool_crop_format: "Target Format",
    tool_crop_btn_only: "Crop Only",
    tool_crop_btn_export: "Crop & Export",
    tool_bg_desc: "Describe new background.",
    tool_bg_placeholder: "e.g. 'tokyo street'",
    tool_bg_btn: "Replace Background",
    tool_style_desc: "Apply style of another image.",
    tool_style_select: "Select Style Image",
    tool_style_btn: "Apply Style",

    tool_social_title: "Social Media Kit",
    tool_social_desc: "AI captions and hashtags for Instagram.",
    tool_social_btn: "Generate Content",

    tool_video_title: "Animate Photo (Veo)",
    tool_video_desc: "Generate video from photo using Veo.",
    tool_video_prompt: "Describe motion",
    tool_video_btn: "Generate Video",

    tool_youtube_title: "YouTube Thumbnails",
    tool_youtube_desc: "Create high-contrast thumbnails.",
    tool_youtube_topic: "Video Topic",
    tool_youtube_topic_ph: "e.g. iPhone 16 Review",
    tool_youtube_text: "Thumbnail Text",
    tool_youtube_text_ph: "e.g. SHOCKING TRUTH",
    tool_youtube_face: "Use current photo as face",
    tool_youtube_btn: "Generate Thumbnail",
    
    manual_title: "Manual Edits",
    manual_reset: "Reset",
    manual_crop_active: "Manual Crop",
    manual_brightness: "Brightness",
    manual_contrast: "Contrast",
    manual_saturation: "Saturation",
    manual_vibrance: "Vibrance",
    manual_shadows: "Shadows",
    manual_highlights: "Highlights",
    manual_clarity: "Clarity",
    manual_sharpness: "Sharpness",
    manual_noise: "Noise Reduction",
    manual_export_settings: "Export Settings",
    manual_finish: "Finish & Export",

    export_title: "Export Image",
    export_format: "Format",
    export_quality: "Quality",
    export_size: "Size",
    export_original: "Original",
    export_half: "Half",
    export_download: "Download",

    batch_title: "Batch Processing",
    batch_subtitle: "Apply AI to multiple images.",
    batch_select: "Select Images",
    batch_selected: "selected",
    batch_select_all: "Select All",
    batch_deselect_all: "Deselect All",
    batch_run: "Run Autopilot",
    batch_processing: "Processing...",
    batch_error: "Error processing",
    batch_complete: "Batch complete.",

    gen_title: "Create with AI",
    gen_subtitle: "Describe and create.",
    gen_prompt: "Prompt",
    gen_placeholder: "e.g. Astronaut on Mars",
    gen_btn: "Generate",
    gen_generating: "Generating...",
    gen_add: "Add to Project",
    
    raw_title: "RAW Converter",
    raw_subtitle: "Bulk RAW to JPEG conversion.",
    raw_convert: "Convert",
    raw_converting: "Converting...",
    raw_add: "Add to Studio",
    raw_convert_more: "Convert More",
    raw_done: "Done",
    raw_drag: "Drag RAW files here",
    raw_or_click: "or click",
    raw_select_other: "Select Other",
    raw_no_files: "No files selected.",
    
    modal_api_title: "API Settings",
    modal_api_desc: "Enter your own API key.",
    modal_api_btn_auto: "Select Key (AI Studio)",
    modal_api_manual_toggle: "Manual Entry",
    modal_api_manual_label: "API Key",
    modal_api_btn_save: "Save",
    modal_api_footer: "Get it for free at",

    msg_api_missing: "API Key missing.",
    msg_success: "Success.",
    msg_error: "Error.",
    notify_upload_success: "files uploaded.",
    notify_gen_success: "Image generated.",
    notify_raw_success: "files prepared.",

    compare_before: "Before",
    compare_after: "After",
    compare_btn: "Compare"
  }
};

type Translations = typeof translations.cs;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('cs');
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useTranslation must be used within a LanguageProvider');
  return context;
};
